version: '2'
services:
  mysql: 
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: rapp_development
  redis: 
    image: redis:alpine
    ports:
      - "6379:6379"
  web:
    build: .
    command: "rackup -o 0.0.0.0 -p 3000"
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - mysql 
      - redis
