version: '2'
services:
  database:
    image: sameersbn/postgresql:9.4-13
    ports:
      - "5432:5432"
    environment:
      DB_USER: 'root'
      DB_PASS: '123456'
      DB_NAME: 'development'
  web:
    build: .
    command: ./scripts/start
    volumes:
      - .:/app
    volumes_from:
      - bundle
    ports:
      - "3000:3000"
    depends_on:
      - database
      - bundle

  bundle:
    image: busybox
    volumes:
      - ./bundle:/bundle
