version: '2'
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: rapp_development
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  web:
    build: .
    command: "shotgun --server=puma --port=3000 -o 0.0.0.0 config.ru"
    volumes:
      - .:/usr/src/app
    volumes_from:
      - bundle
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis
      - bundle

  bundle:
    image: busybox
    command: echo "I'm a little data container, short and stout..."
    volumes:
      - .:/bundle
